sudo: required
services:
  - docker

before_install:
  - docker build -f Dockerfile.dev -t arodko/docker-react .

script:
  - docker run -e CI=true arodko/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "Docker-react-env-1"
  bucket_name: "elasticbeanstalk-us-east-1-424371521123"
  bucket_path: ""docker-react"
  on:
    branch: master
  access_key_id: $AWS+ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"

